# Generated by Django 2.0.9 on 2019-01-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(blank=True, help_text='Enter phone number with country code', max_length=13, null=True),
        ),
    ]
