# Generated by Django 2.1.1 on 2018-12-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181213_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('add_staff', 'Can add staff'), ('accept_request', 'Can accept leave request'), ('make_request', 'can make leave request'))},
        ),
    ]
