# Generated by Django 2.0.9 on 2018-12-14 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181213_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.TimeField(auto_now=True)),
                ('check_in_date', models.DateField(auto_now=True)),
                ('check_out', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(default='Management', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Describe your leave request', null=True)),
                ('date_submission', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('supervisor', 'Supervisor'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypesOfLeave',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(blank=True, choices=[('sick_leave', 'Sick Leave'), ('annual_leave', 'Annual Leave')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_taken', models.IntegerField(default=0)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TypesOfLeave')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('add_staff', 'Can add staff'), ('accept_request', 'Can accept leave request'), ('make_request', 'can make leave request'), ('set_roles_of_staff', 'can set roles of staff'), ('view_attendance', 'can veiw attendance'))},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userdays',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='responded_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(default='Management', on_delete=django.db.models.deletion.CASCADE, to='users.Branch'),
        ),
    ]
