# Generated by Django 2.0.9 on 2018-12-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='typesofleave',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('annual_leave', 'Annual Leave'), ('sick_leave', 'Sick Leave')], max_length=255, null=True),
        ),
    ]
