# Generated by Django 2.0.9 on 2019-01-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20190120_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdays',
            old_name='days_taken',
            new_name='days_left',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=255),
        ),
    ]
