# Generated by Django 2.0.9 on 2018-12-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20181221_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(blank=True, choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('approved', 'Approved')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='typesofleave',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('sick_leave', 'Sick Leave'), ('annual_leave', 'Annual Leave')], max_length=255, null=True),
        ),
    ]
