# Generated by Django 2.0.9 on 2018-12-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20181223_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='typesofleave',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('annual_leave', 'Annual Leave'), ('sick_leave', 'Sick Leave')], max_length=255, null=True),
        ),
    ]
