# Generated by Django 2.0.9 on 2018-12-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20181223_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='typesofleave',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('sick_leave', 'Sick Leave'), ('annual_leave', 'Annual Leave')], max_length=255, null=True),
        ),
    ]
